matrix:
  - name: Markdown
    aspell:
      ignore-case: true
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - '_tools/*.md'
      - '_events/*.md'
