title: OSCAL.io
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: Easy Dynamics Corp
copyrightyear: "2023"
contactemail: oscal@easydynamics.com
ga4code: "G-532JFQZHHC"

collections:
  events:
    sort_by: start-date
    output: true
  tools:
    sort_by: author
    output: true

defaults:
  - scope:
      path: ''
      type: events
    values:
      layout: event-details
  - scope:
      path: ''
      type: tools
    values:
      layout: tool-details

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.*
